# PyTorch Fundamental:
<a id='h_cell'></a>
Tensors are the central data abstraction in PyTorch. This interactive notebook provides an in-depth introduction to the `torch.Tensor` class. You can run this notebook locally, on [Colab](https://colab.research.google.com/), or on your preferred cloud service.

|#NO|Topic|Status|
|--:|:---          |--:|
|01| [Terminology](#ter_cell)||
|02| [Getting information](#gi_cell)|
|03| [***Tensor Random***](#random_cell)|
|04| [***Create Tensor***](#ctensor_cell)|
|05| [Tensor Data Type](#dtype_cell)|
|06| [***Math and Logic with Pytorch***](#math_cell)|
|07| [***Manipulating Tensor Shape or Braodcasting***](#mts_cell)|
|08| [***Array Accessing***](#aa_cell)|
|09| [***Frequently used method***](#im_cell)|
|10| [***Moving to GPU***](#gpu_cell)|
|11| [***Numpy Bridge***](#npb_cell)|

In [2]:
import torch
import math

## [1. Terminology](#h_cell)
<a id='ter_cell'></a>

A brief note about tensors and their number of dimensions, and terminology:

1. O-dimensional tensor called a \*scaler.
2. 1-dimensional tensor called a \*vector.
3. Likewise, a 2-dimensional tensor is often referred to as a \*matrix.
4. Anything with more than two dimensions is generally just called a tensor.

1. Scaler:


In [74]:
scaler = torch.tensor(7)
scaler.ndim, scaler.shape, scaler.item(), scaler, type(scaler)

(0, torch.Size([]), 7, tensor(7), torch.Tensor)

2. Vector:


In [77]:
vector = torch.tensor([7, 8])
print(type(vector))
vector, vector.ndim, vector.shape

<class 'torch.Tensor'>


(tensor([7, 8]), 1, torch.Size([2]))

**Note:** Here torch.Size([2]) means the vector has a shape 2 state that there are two items.


3. Matrix:


In [76]:
## Matrix
MATRIX = torch.tensor([[7, 8], [9, 10]])
print(type(MATRIX))
MATRIX, MATRIX.shape, MATRIX.ndim, MATRIX.dtype

<class 'torch.Tensor'>


(tensor([[ 7,  8],
         [ 9, 10]]),
 torch.Size([2, 2]),
 2,
 torch.int64)

4. **Tensor or Multi-dimentional:**


In [120]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR, TENSOR.shape, TENSOR.ndim

(tensor([[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]),
 torch.Size([1, 3, 3]),
 3)

In [4]:
tensor= torch.tensor([[[1, 2, 3,4], [4, 5, 6,4]], [[7, 8, 9,4], [10, 11, 12,4]], [[13, 14, 15,4], [16, 17, 18,4]]])
tensor.size, tensor.shape, tensor.ndim

(<function Tensor.size>, torch.Size([3, 2, 4]), 3)

## [2. Getting Information](#h_cell)
<a id='gi_cell'></a>

1. type(x): type(tensor) will return the type of the tensor object.
2. x.dtype: tensor.dtype will give you the data type.
3. x.shape: tensor.shape will give you the shape of the tensor.
4. x.size(): tensor.size() will give you the total number of elements.
5. x.ndim: The ndim attribute of a PyTorch tensor returns the number of dimensions (rank) of the tensor.
6. x.device: tensor.device will give you the device information.
7. x.requires_grad: indicates whether the tensor requires gradient computation for backpropagation during training.


In [125]:
# Create a tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

print(type(tensor))  # Get type of the tensor
print(tensor.dtype)  # Get data type of the tensor
print(tensor.shape)  # Get shape of the tensor
print(tensor.size())  # Get total number of elements in the tensor
print(tensor.ndim)  # Get number of dimensions of the tensor
print(tensor.device)  # Get device information of the tensor
print(tensor.requires_grad)  # Check if tensor requires gradient computation

<class 'torch.Tensor'>
torch.int64
torch.Size([2, 3])
torch.Size([2, 3])
2
cpu
False


## [3. Random Tensors and Seeding:](#h_cell)
<a id='random_cell'></a>

Speaking of the random tensor, did you notice the call to `torch.manual_seed()` immediately preceding it? Initializing tensors, such as a model's learning weights, with random values is common but there are times - especially in research settings - where you'll want some assurance of the reproducibility of your results. Manually setting your random number generator's seed is the way to do this. Let's look more closely:


In [66]:
torch.manual_seed(123)
torch_random = torch.rand([2, 3, 3], dtype=torch.float)  # same as torch.random(2,3,3)
torch_random.shape, torch_random.ndim, torch_random, torch_random[0][0], torch_random[
    1
][1][2]

(torch.Size([2, 3, 3]),
 3,
 tensor([[[0.2961, 0.5166, 0.2517],
          [0.6886, 0.0740, 0.8665],
          [0.1366, 0.1025, 0.1841]],
 
         [[0.7264, 0.3153, 0.6871],
          [0.0756, 0.1966, 0.3164],
          [0.4017, 0.1186, 0.8274]]]),
 tensor([0.2961, 0.5166, 0.2517]),
 tensor(0.3164))

In [58]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


What you should see above is that `random1` and `random3` carry identical values, as do `random2` and `random4`. Manually setting the RNG's seed resets it, so that identical computations depending on random number should, in most settings, provide identical results.

For more information, see the [PyTorch documentation on reproducibility](https://pytorch.org/docs/stable/notes/randomness.html).


In [67]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.3821, 0.6605, 0.8536, 0.5932],
         [0.6367, 0.9826, 0.2745, 0.6584],
         [0.2775, 0.8573, 0.8993, 0.0390]]),
 torch.float32)

In [6]:
## image shape of [224, 224, 3] ([height, width, color_channels]).
image = torch.rand(224, 244, 3)
image[1], image.shape, image.ndim, image.dtype, type(image)

(tensor([[3.4346e-01, 1.1412e-01, 3.7161e-02],
         [6.7748e-01, 9.5072e-01, 5.7306e-01],
         [8.2716e-01, 3.6313e-01, 9.8644e-01],
         [3.5969e-01, 6.9106e-01, 6.5847e-01],
         [7.8675e-01, 5.9714e-01, 7.1090e-01],
         [5.4176e-01, 6.0740e-01, 6.1512e-01],
         [2.6526e-01, 2.3738e-01, 8.3565e-01],
         [5.8544e-01, 8.6992e-01, 6.1827e-02],
         [6.7257e-01, 8.0526e-01, 5.2741e-01],
         [8.4499e-02, 6.1248e-01, 9.6163e-01],
         [1.5855e-01, 2.4873e-01, 9.1681e-01],
         [2.4133e-01, 6.4243e-01, 6.3256e-01],
         [5.2445e-01, 5.7729e-01, 4.5339e-01],
         [4.8180e-01, 3.3952e-02, 7.6372e-01],
         [9.5316e-01, 8.2589e-01, 2.0838e-01],
         [5.8818e-01, 3.2247e-01, 6.9899e-01],
         [2.4950e-01, 4.5095e-01, 3.6715e-02],
         [4.2967e-01, 8.1858e-01, 5.4694e-01],
         [2.7438e-01, 1.7958e-01, 2.2569e-01],
         [7.2946e-01, 7.3824e-01, 3.0567e-01],
         [6.7375e-01, 9.6540e-01, 1.4697e-01],
         [3.2

## [4. Creating Tensors](#h_cell)
<a id='ctensor_cell'></a>

1. `torch.tensor()`: create a tensor object.
2. `torch.random()`: create a random tensor with given shape.
3. `torch.ones()`: create a tensor with one.
4. `torch.zeors()`: create a tensor with $0$
5. `torch.arange(start, end, step)`:
6. `torch.empty()`: The `torch.empty()` call allocates memory for the tensor, but does not initialize it with any values - so what you're seeing is whatever was in memory at the time of allocation.
7. ``torch.*_like(x)`: Often, when you're performing operations on two or more tensors, they will need to be of the same _shape_ - that is, having the same number of dimensions and the same number of cells in each dimension. For that, we have the `torch.*_like()` methods.
   1. `torch.empty_like(x):`
   2. `torch.zeros_like(x):`
   3. `torch.empty_like(x):`
   4. `torch.rand_like()`:

_Note: `torch.tensor()` creates a copy of the data._


In [8]:
zeros = torch.zeros(2,3)
print(zeros, zeros.shape)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

x = torch.empty(size=(3, 4))
print(type(x))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
<class 'torch.Tensor'>
tensor([[0.0000, 1.8750, 0.0000, 1.8750],
        [0.0000, 1.8750, 0.0000, 1.8750],
        [0.0000, 1.8750, 0.0000, 1.8750]])


In [8]:
# torch.arrange():
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
## torch.*_like()
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(type(rand_like_x))

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
<class 'torch.Tensor'>


Let's unpack what we just did:

- The tensor itself is 2-dimensional, having 3 rows and 4 columns.
- The type of the object returned is `torch.Tensor`, which is an alias for `torch.FloatTensor`; by default, PyTorch tensors are populated with 32-bit floating point numbers. (More on data types below.)


In [6]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


## [5. Tensor Data type:](#h_cell)
<a id='dtype_cell'></a>

Setting the datatype of a tensor is possible a couple of ways:


In [9]:
a = torch.ones((2, 3), dtype=torch.int16)

b = torch.rand((2, 3), dtype=torch.float64) * 20.0

c = b.to(torch.int32)

a, b, c

(tensor([[1, 1, 1],
         [1, 1, 1]], dtype=torch.int16),
 tensor([[17.3151, 14.5980,  6.0404],
         [18.0429,  7.2532, 19.6519]], dtype=torch.float64),
 tensor([[17, 14,  6],
         [18,  7, 19]], dtype=torch.int32))

The simplest way to set the underlying data type of a tensor is with an optional argument at creation time. In the first line of the cell above, we set `dtype=torch.int16` for the tensor `a`. When we print `a`, we can see that it's full of `1` rather than `1.` - Python's subtle cue that this is an integer type rather than floating point.

Another thing to notice about printing `a` is that, unlike when we left `dtype` as the default (32-bit floating point), printing the tensor also specifies its `dtype`.

You may have also spotted that we went from specifying the tensor's shape as a series of integer arguments, to grouping those arguments in a tuple. This is not strictly necessary - PyTorch will take a series of initial, unlabeled integer arguments as a tensor shape - but when adding the optional arguments, it can make your intent more readable.

The other way to set the datatype is with the `.to()` method. In the cell above, we create a random floating point tensor `b` in the usual way. Following that, we create `c` by converting `b` to a 32-bit integer with the `.to()` method. Note that `c` contains all the same values as `b`, but truncated to integers.

Available data types include:

- `torch.bool`
- `torch.int8`
- `torch.uint8`
- `torch.int16`
- `torch.int32`
- `torch.int64`
- `torch.half`
- `torch.float`
- `torch.double`
- `torch.bfloat`


In [10]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None,  # defaults to None, which is torch.float32 or whatever datatype is passed
    device=None,  # defaults to None, which uses the default tensor type
    requires_grad=False,
)  # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

## [6. Math & Logic with PyTorch](#h_cell)
<a id='math_cell'></a>

Now that you know some of the ways to create a tensor... what can you do with them?

Let's look at basic arithmetic first, and how tensors interact with simple scalars:


In [87]:
ones = torch.zeros(2, 2) + 1  # addition ones.add()
ones = ones.add(100)
twos = torch.ones(2, 2) * 2  # multiplication
threes = (torch.ones(2, 2) * 7 - 1) / 2  # complex operation
fours = twos**2  # squre
sqrt2s = twos**0.5  ## squre root

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[101., 101.],
        [101., 101.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


Similar operations between two tensors also behave like you'd intuitively expect:


In [88]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours  # element wise multiplication
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[105., 105.],
        [105., 105.]])
tensor([[12., 12.],
        [12., 12.]])


### 6.1 Matrix multiplication

PyTorch implements matrix multiplication functionality in the `torch.matmul()` method.

1.  The inner dimensions must match:

        (3, 2) @ (3, 2) won't work
        (2, 3) @ (3, 2) will work
        (3, 2) @ (2, 3) will work

2.  The resulting matrix has the shape of the outer dimensions:

        (2, 3) @ (3, 2) -> (2, 2)
        (3, 2) @ (2, 3) -> (3, 3)

### 6.2 Element wise multiplication:

PyTorch implements multiplication functionality in the `torch.mul()` or `*` method.

        (3, 2) @ (2, 3) won't work
        (2, 3) @ (3, 3) will work
$$[m\times n\times o] * [p\times q\times r]=[m\times n\times o]\text{ this will be the new shape}$$
* Each tensor must have at least one dimension - no empty tensors.
* Comparing the dimension sizes of the two tensors, **going from last to first:**
    * Each dimension must be equal $m=p\;, n=q,\; o=r $, **or**
    * One of the dimensions must be of size 1, $p=1\;, q=1,\; o=r=1 $**or**
    * The dimension does not exist in one of the tensors $q=1,\; o=r=1 $


In [97]:
tensor = torch.tensor([1, 2, 3])
print(tensor.shape, tensor.ndim)
element_wise_mul = (
    tensor * tensor
)  # Element wise multiplication: [1*1, 2*2, 3*3]=[1, 4, 9]
print("Element-Wise-Multiplication", element_wise_mul)
print("Element-Wise-Multiplication: torch.mul()", torch.mul(tensor, tensor))

print("Matrix-Multiplication:", torch.matmul(tensor, tensor))

torch.Size([3]) 1
Element-Wise-Multiplication tensor([1, 4, 9])
Element-Wise-Multiplication: torch.mul() tensor([1, 4, 9])
Matrix-Multiplication: tensor(14)


In [21]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]], dtype=torch.float32)
print(f"tensor_A: {tensor_A.shape} \t {tensor_A.ndim}")
print(f"tensor_B: {tensor_B.shape} \t {tensor_B.ndim}")

print("Element wise:", torch.mul(tensor_A, tensor_B))
print("Transpose:", tensor_A.T.shape)

mat = torch.matmul(tensor_A.T, tensor_B)
print("mat:", mat.shape, "\n ", mat)
mat_1 = torch.matmul(tensor_A, tensor_B.T)
print("mat:", mat_1.shape, "\n ", mat_1)

tensor_A: torch.Size([3, 2]) 	 2
tensor_B: torch.Size([3, 2]) 	 2
Element wise: tensor([[ 7., 20.],
        [24., 44.],
        [45., 72.]])
Transpose: torch.Size([2, 3])
mat: torch.Size([2, 2]) 
  tensor([[ 76., 103.],
        [100., 136.]])
mat: torch.Size([3, 3]) 
  tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


#### Element wise Multiplication:

- Each tensor must have at least one dimension - no empty tensors.
- Comparing the dimension sizes of the two tensors, _going from last to first:_
- - Each dimension must be equal, _or_
- - One of the dimensions must be of size 1, _or_
- - The dimension does not exist in one of the tensors


In [17]:
import torch

a = torch.ones(4, 3, 2)
b = a * torch.rand(2)  # 3rd & 2nd dims identical to a, dim 1 absent
print(b)
c = a * torch.rand(1, 2)  # 3rd dim = 1, 2nd dim identical to a
print(c)
d = a * torch.rand(1, 2)  # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.7220, 0.8217],
         [0.7220, 0.8217],
         [0.7220, 0.8217]],

        [[0.7220, 0.8217],
         [0.7220, 0.8217],
         [0.7220, 0.8217]],

        [[0.7220, 0.8217],
         [0.7220, 0.8217],
         [0.7220, 0.8217]],

        [[0.7220, 0.8217],
         [0.7220, 0.8217],
         [0.7220, 0.8217]]])
tensor([[[0.2612, 0.7375],
         [0.2612, 0.7375],
         [0.2612, 0.7375]],

        [[0.2612, 0.7375],
         [0.2612, 0.7375],
         [0.2612, 0.7375]],

        [[0.2612, 0.7375],
         [0.2612, 0.7375],
         [0.2612, 0.7375]],

        [[0.2612, 0.7375],
         [0.2612, 0.7375],
         [0.2612, 0.7375]]])
tensor([[[0.8328, 0.8444],
         [0.8328, 0.8444],
         [0.8328, 0.8444]],

        [[0.8328, 0.8444],
         [0.8328, 0.8444],
         [0.8328, 0.8444]],

        [[0.8328, 0.8444],
         [0.8328, 0.8444],
         [0.8328, 0.8444]],

        [[0.8328, 0.8444],
         [0.8328, 0.8444],
         [0.8328, 0.8444]]])


In [13]:
a = torch.ones(4, 3, 2)

b = a * torch.rand(4, 2)  # dimensions must match last-to-first

c = a * torch.rand(2, 3)  # both 3rd & 2nd dims different

d = a * torch.rand((0,))  # can't broadcast with an empty tensor

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

### 6.3 More Math with Tensors

PyTorch tensors have over three hundred operations that can be performed on them.

Here is a small sample from some of the major categories of operations:


#### 6.3.1 Common Function:

1. `torch.abs(x):` computes the element-wise absolute value of a tensor
1. `torch.ceil(x):` rounds each element of a tensor upward to the nearest integer.
1. `torch.floor(x):`rounds each element of a tensor downward to the nearest integer.
1. `torch.clamp(x,min, max):` clamps each element of a tensor to a specified range defined by a minimum and maximum value.


In [23]:
# common functions
a = torch.rand(2, 4) * 2 - 1
print("Common functions:")
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

Common functions:
tensor([[0.0110, 0.2285, 0.9767, 0.0476],
        [0.4484, 0.8447, 0.1992, 0.9755]])
tensor([[-0., -0., 1., -0.],
        [1., -0., -0., 1.]])
tensor([[-1., -1.,  0., -1.],
        [ 0., -1., -1.,  0.]])
tensor([[-0.0110, -0.2285,  0.5000, -0.0476],
        [ 0.4484, -0.5000, -0.1992,  0.5000]])


#### 6.3.2 Aggregation

1. `min, max, mean, sum`
2. `torch.argmax(x):`
3. `torch.argmin(x):`


In [26]:
x = torch.arange(0, 100, 10)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}")  # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [27]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


This is a small sample of For more details and the full inventory of math functions, have a look at the [documentation](https://pytorch.org/docs/stable/torch.html#math-operations).


In [28]:
# # trigonometric functions and their inverses
# angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
# sines = torch.sin(angles)
# inverses = torch.asin(sines)
# print('\nSine and arcsine:')
# print(angles)
# print(sines)
# print(inverses)

# # bitwise operations
# print('\nBitwise XOR:')
# b = torch.tensor([1, 5, 11])
# c = torch.tensor([2, 7, 10])
# print(torch.bitwise_xor(b, c))

# # comparisons:
# print('\nBroadcasted, element-wise equality comparison:')
# d = torch.tensor([[1., 2.], [3., 4.]])
# e = torch.ones(1, 2)  # many comparison ops support broadcasting!
# print(torch.eq(d, e)) # returns a tensor of type bool

# # reductions:
# print('\nReduction ops:')
# print(torch.max(d))        # returns a single-element tensor
# print(torch.max(d).item()) # extracts the value from the returned tensor
# print(torch.mean(d))       # average
# print(torch.std(d))        # standard deviation
# print(torch.prod(d))       # product of all numbers
# print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements

# # vector and linear algebra operations
# v1 = torch.tensor([1., 0., 0.])         # x unit vector
# v2 = torch.tensor([0., 1., 0.])         # y unit vector
# m1 = torch.rand(2, 2)                   # random matrix
# m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

# print('\nVectors & Matrices:')
# print(torch.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
# print(m1)
# m3 = torch.matmul(m1, m2)
# print(m3)                  # 3 times m1
# print(torch.svd(m3))       # singular value decomposition

## [7. Manipulating Tensor Shapes:](#h_cell)
<a id='mts_cell'></a>

1. `torch.reshape(input, shape):` Reshapes input to shape (if compatible) and explicitly create a new tensor with a modified shape or rearranged memory layout
2. `torch.Tensor.view(shape):`Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
3. `torch.stack(tensors, dim=0):`Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
4. `torch.squeeze(input):` Squeezes input to remove all the dimenions with value 1.
5. `torch.unsqueeze(input, dim):`Returns input with a dimension value of 1 added at dim.
6. `torch.permute(input, dims):`Returns a view of the original input with its dimensions permuted (rearranged) to dims.
7. Altering Orginal Tensor:


In [16]:
# reshape
image=torch.rand(2,3,28,28)
reshape1=image.reshape(image.shape[0],-1) #flatten the image
reshape2=image.reshape(-1)
reshape1, reshape1.shape,3*28*28, reshape2, reshape2.shape

(tensor([[0.2103, 0.5611, 0.6405,  ..., 0.5529, 0.1800, 0.6779],
         [0.9662, 0.9604, 0.1740,  ..., 0.3192, 0.9305, 0.4690]]),
 torch.Size([2, 2352]),
 2352,
 tensor([0.2103, 0.5611, 0.6405,  ..., 0.3192, 0.9305, 0.4690]),
 torch.Size([4704]))

When it can, `reshape()` will return a _view_ on the tensor to be changed - that is, a separate tensor object looking at the same underlying region of memory. _This is important:_ That means any change made to the source tensor will be reflected in the view on that tensor, unless you `clone()` it.

In [22]:
# view:
# Create a 2x3 tensor
original_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Reshape the tensor to be 3x2
reshaped_tensor = original_tensor.view(6, 1)

print(original_tensor)
print(reshaped_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [25]:
# Create three tensors
tensor1 = torch.tensor([1, 2,2])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack them along a new dimension (default is dim=0)
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])

print(stacked_tensor)

tensor([[1, 2, 2],
        [4, 5, 6],
        [7, 8, 9]])


In [28]:
# permute
original_tensor = torch.arange(24).reshape(3, 4, 2)

# Permute the dimensions to change the order
permuted_tensor = original_tensor.permute(1, 0, 2)

print(original_tensor, original_tensor.shape)  # Output: torch.Size([3, 4, 2])
print(permuted_tensor,permuted_tensor.shape)  # Output: torch.Size([2, 3, 4])

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]) torch.Size([3, 4, 2])
tensor([[[ 0,  1],
         [ 8,  9],
         [16, 17]],

        [[ 2,  3],
         [10, 11],
         [18, 19]],

        [[ 4,  5],
         [12, 13],
         [20, 21]],

        [[ 6,  7],
         [14, 15],
         [22, 23]]]) torch.Size([4, 3, 2])


In [38]:
import torch

x = torch.arange(1.0, 8.0)
y = torch.arange(1.0, 8.0)

print(x, x.shape)
x_reshaped = x.reshape(1, 7)
print("reshape():", x_reshaped, x_reshaped.shape)
print("after reshape- X:", x, x.shape)
x_reshaped[:, 1] = 200
print("reshape():", x_reshaped, x_reshaped.shape)
print("after reshape- X:", x, x.shape)

print("using view:")
z_viewed = y.view(1, 7)
print("view():", z_viewed, z_viewed.shape)
print("after view -> y:", y, y.shape)
z_viewed[:, 1] = 200
print("view():", z_viewed, z_viewed.shape)
print("after view -> y:", y, y.shape)

tensor([1., 2., 3., 4., 5., 6., 7.]) torch.Size([7])
reshape(): tensor([[1., 2., 3., 4., 5., 6., 7.]]) torch.Size([1, 7])
after reshape- X: tensor([1., 2., 3., 4., 5., 6., 7.]) torch.Size([7])
reshape(): tensor([[  1., 200.,   3.,   4.,   5.,   6.,   7.]]) torch.Size([1, 7])
after reshape- X: tensor([  1., 200.,   3.,   4.,   5.,   6.,   7.]) torch.Size([7])
using view:
view(): tensor([[1., 2., 3., 4., 5., 6., 7.]]) torch.Size([1, 7])
after view -> y: tensor([1., 2., 3., 4., 5., 6., 7.]) torch.Size([7])
view(): tensor([[  1., 200.,   3.,   4.,   5.,   6.,   7.]]) torch.Size([1, 7])
after view -> y: tensor([  1., 200.,   3.,   4.,   5.,   6.,   7.]) torch.Size([7])


In [57]:
### stack(input,dimen)
a = torch.arange(1, 10, 1)
b = torch.rand(2, 2)
# a_stack= torch.stack([a,a,b], dim=0) #tack expects each tensor to be equal size, but got [9] at entry 0 and [2, 2] at entry 2
a_stack = torch.stack([a, a, a], dim=0)
print(a_stack, a_stack.shape)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([3, 9])


In [81]:
a = torch.tensor([[[1, 2, 33, 4, 5]]])
print(f"tensor: {a}\t  shape: {a.shape}")

# Remove extra dimension from a
a_squeezed = a.squeeze(dim=1)
print(f"\nNew tensor: {a_squeezed}\t New shape: {a_squeezed.shape}")
a_squeezed = torch.squeeze(a_squeezed)
print(f"\nNew tensor: {a_squeezed}\t New shape: {a_squeezed.shape}")

a_unsqueezed = a_squeezed.unsqueeze(dim=0)
print(f"\nUnsques-1 tensor: {a_unsqueezed}\t New shape: {a_unsqueezed.shape}")

tensor: tensor([[[ 1,  2, 33,  4,  5]]])	  shape: torch.Size([1, 1, 5])

New tensor: tensor([[ 1,  2, 33,  4,  5]])	 New shape: torch.Size([1, 5])

New tensor: tensor([ 1,  2, 33,  4,  5])	 New shape: torch.Size([5])

Unsques-1 tensor: tensor([[ 1,  2, 33,  4,  5]])	 New shape: torch.Size([1, 5])


In [18]:
#unsqueeze
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


#### 7.7 Altering Tensors in Place

Most binary operations on tensors will return a third, new tensor. When we say `c = a * b` (where `a` and `b` are tensors), the new tensor `c` will occupy a region of memory distinct from the other tensors.

There are times, though, that you may wish to alter a tensor in place - for example, if you're doing an element-wise computation where you can discard intermediate values. For this, most of the math functions have a version with an appended underscore (`_`) that will alter a tensor in place.

For example:


In [16]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print("Before:")
print(a)
print(b)
print("\nAfter adding:")
print(a.add_(b))
print(a)
print(b)
print("\nAfter multiplying")
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.8441, 0.9004],
        [0.3995, 0.6324]])

After adding:
tensor([[1.8441, 1.9004],
        [1.3995, 1.6324]])
tensor([[1.8441, 1.9004],
        [1.3995, 1.6324]])
tensor([[0.8441, 0.9004],
        [0.3995, 0.6324]])

After multiplying
tensor([[0.7125, 0.8107],
        [0.1596, 0.3999]])
tensor([[0.7125, 0.8107],
        [0.1596, 0.3999]])


Note that these in-place arithmetic functions are methods on the `torch.Tensor` object, not attached to the `torch` module like many other functions (e.g., `torch.sin()`). As you can see from `a.add_(b)`, _the calling tensor is the one that gets changed in place._

There is another option for placing the result of a computation in an existing, allocated tensor. Many of the methods and functions we've seen so far - including creation methods! - have an `out` argument that lets you specify a tensor to receive the output. If the `out` tensor is the correct shape and `dtype`, this can happen without a new memory allocation:


In [85]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)  # contents of c have changed

assert (
    c is d
), "Not equal"  # test c & d are same object, not just containing equal values
assert id(c), old_id  # make sure that our new c is the same object as the old one

torch.rand(2, 2, out=c)  # works for creation too!
print(c)  # c has changed again
assert id(c), old_id  # still the same object!

tensor([[0., 0.],
        [0., 0.]])
tensor([[1.0902, 0.5189],
        [0.2020, 0.1123]])
tensor([[0.1779, 0.7497],
        [0.9760, 0.5971]])


#### 7.8 Copying Tensors

As with any object in Python, assigning a tensor to a variable makes the variable a _label_ of the tensor, and does not copy it. For example:


In [18]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561  # we change a...
print(b)  # ...and b is also altered

tensor([[  1., 561.],
        [  1.,   1.]])


But what if you want a separate copy of the data to work on? The `clone()` method is there for you:


In [19]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a  # different objects in memory...
print(torch.eq(a, b))  # ...but still with the same contents!

a[0][1] = 561  # a changes...
print(b)  # ...but b is still all ones

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


**There is an important thing to be aware of when using `clone()`.** If your source tensor has autograd, enabled then so will the clone.

_In many cases, this will be what you want._ For example, if your model has multiple computation paths in its `forward()` method, and _both_ the original tensor and its clone contribute to the model's output, then to enable model learning you want autograd turned on for both tensors. If your source tensor has autograd enabled (which it generally will if it's a set of learning weights or derived from a computation involving the weights), then you'll get the result you want.

On the other hand, if you're doing a computation where _neither_ the original tensor nor its clone need to track gradients, then as long as the source tensor has autograd turned off, you're good to go.

_There is a third case,_ though: Imagine you're performing a computation in your model's `forward()` function, where gradients are turned on for everything by default, but you want to pull out some values mid-stream to generate some metrics. In this case, you _don't_ want the cloned copy of your source tensor to track gradients - performance is improved with autograd's history tracking turned off. For this, you can use the `.detach()` method on the source tensor:


In [20]:
a = torch.rand(2, 2, requires_grad=True)  # turn on autograd
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)

tensor([[0.5461, 0.5396],
        [0.3053, 0.1973]], requires_grad=True)
tensor([[0.5461, 0.5396],
        [0.3053, 0.1973]], grad_fn=<CloneBackward>)
tensor([[0.5461, 0.5396],
        [0.3053, 0.1973]])
tensor([[0.5461, 0.5396],
        [0.3053, 0.1973]], requires_grad=True)


What's happening here?

- We create `a` with `requires_grad=True` turned on. **We haven't covered this optional argument yet, but will during the unit on autograd.**
- When we print `a`, it informs us that the property `requires_grad=True` - this means that autograd and computation history tracking are turned on.
- We clone `a` and label it `b`. When we print `b`, we can see that it's tracking its computation history - it has inherited `a`'s autograd settings, and added to the computation history.
- We clone `a` into `c`, but we call `detach()` first.
- Printing `c`, we see no computation history, and no `requires_grad=True`.

The `detach()` method _detaches the tensor from its computation history._ It says, "do whatever comes next as if autograd was off." It does this _without_ changing `a` - you can see that when we print `a` again at the end, it retains its `requires_grad=True` property.

## [8. Tensor Accessing](#h_cell)
<a id='aa_cell'></a>

## [9. Important Methods:](#h_cell)
<a id='im_cell'></a>

## [10. Moving to GPU](#h_cell)
<a id='gpu_cell'></a>

One of the major advantages of PyTorch is its robust acceleration on CUDA-compatible Nvidia GPUs. ("CUDA" stands for _Compute Unified Device Architecture_, which is Nvidia's platform for parallel computing.)

First, we should check whether a GPU is available, with the `is_available()` method.

**Note: If you do not have a CUDA-compatible GPU and CUDA drivers installed, the executable cells in this section will not execute any GPU-related code.**


In [21]:
if torch.cuda.is_available():
    print("We have a GPU!")
else:
    print("Sorry, CPU only.")

Sorry, CPU only.


In [23]:
if torch.cuda.is_available():
    my_device = torch.device("cuda")
else:
    my_device = torch.device("cpu")
print("Device: {}".format(my_device))

x = torch.rand(2, 2, device=my_device)
print(x)

Device: cpu
tensor([[0.3285, 0.5655],
        [0.0065, 0.7765]])


If you have an existing tensor living on one device, you can move it to another with the `to()` method. The following line of code creates a tensor on CPU, and moves it to whichever device handle you acquired in the previous cell.


In [24]:
y = torch.rand(2, 2)
y = y.to(my_device)

It is important to know that in order to do computation involving two or more tensors, _all of the tensors must be on the same device_. The following code will throw a runtime error, regardless of whether you have a GPU device available:

```
x = torch.rand(2, 2)
y = torch.rand(2, 2, device='gpu')
z = x + y  # exception will be thrown
```


## [11. NumPy Bridge](#h_cell)
<a id='npb_cell'></a>

In [31]:
import numpy as np

numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


PyTorch creates a tensor of the same shape and containing the same data as the NumPy array, going so far as to keep NumPy's default 64-bit float data type.

The conversion can just as easily go the other way:


In [32]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.5647, 0.9160, 0.7783],
        [0.8277, 0.4579, 0.6382]])
[[0.5646949  0.91600937 0.77828014]
 [0.82769746 0.45785618 0.6381657 ]]


It is important to know that these converted objects are using _the same underlying memory_ as their source objects, meaning that changes to one are reflected in the other:


In [33]:
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.5646949   0.91600937  0.77828014]
 [ 0.82769746 17.          0.6381657 ]]
