
#### [1. Hessian matrix:](https://www.khanacademy.org/math/multivariable-calculus/applications-of-multivariable-derivatives/quadratic-approximations/v/the-hessian-matrix)
The Hessian matrix is a way of organizing all the second partial derivative information of a multivariable function.

***KeyPoints:***
1. Most of the cases the diagonal wil be same.
2. Its matrix valed function.

#### [2. Jacobian Matrix:](https://www.khanacademy.org/math/multivariable-calculus/multivariable-derivatives/jacobian/v/the-jacobian-matrix)
The Jacobian matrix is a matrix of first-order partial derivatives. It provides information about the rate of change of a vector-valued function with respect to its individual variables.
[Austin Blog](https://web.ma.utexas.edu/users/m408s/m408d/CurrentWeb/LM15-10-4.php#:~:text=our%20Jacobian%20is%20%7C%E2%88%82x,rdrd%CE%B8.)

In [6]:
import torch

1. Gradient Calculation

In [10]:
torch.manual_seed(100)
dim=3
x= torch.rand(dim, requires_grad=True) # create a computational graph
print(x)
y=x+2
z= y*y+5
print(y)
v=torch.rand(dim)
# z=z.mean() # output
# here don't need to pass any value beacuse z has a scaler value
z.backward(v) # dz/dx; we have to pass a vector if the the element is not scaler
print(z)
print(x.grad)


tensor([0.1117, 0.8158, 0.2626], requires_grad=True)
tensor([2.1117, 2.8158, 2.2626], grad_fn=<AddBackward0>)
tensor([ 9.4591, 12.9290, 10.1192], grad_fn=<AddBackward0>)
tensor([2.0436, 3.8099, 3.4115])


2. Gradient History:
    1. `requires_grad=False:`
    2. `detach():`
    3. `with torch.no_grad()`

In [23]:
dim=3
x= torch.rand(dim, requires_grad=True) # create a computational graph
print(x)
y= x.detach()
print(y)
with torch.no_grad():
    z=x+2
    print(z)
print(x.requires_grad_(False))
print(x)




tensor([0.6476, 0.3430, 0.3182], requires_grad=True)
tensor([0.6476, 0.3430, 0.3182])
tensor([2.6476, 2.3430, 2.3182])
tensor([0.6476, 0.3430, 0.3182])
tensor([0.6476, 0.3430, 0.3182])


3. Training Example:

In [28]:
dim=4
w= torch.rand(dim, requires_grad=True) # create a computational graph

for epoch in range(3):
    model_output=(w*3).sum()

    model_output.backward()

    print(w.grad)
    w.grad.zero_() # this is an important step to calculate the grad correctly

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
