In [2]:
import tensorflow as tf

print(tf.__version__)

2.12.0


# TensorFlow:

TensorFlow is an open-source end-to-end machine learning library for preprocessing data, modelling data and serving models

1. Terminology
2. Getting information
3. Tensor Random
4. Create Tensor
5. Tensor Data type
6. Math and Logic with Pytorch
7. Manipulating Tensor Shapes


### 1. Terminology

A brief note about tensors and their number of dimensions, and terminology:

1. O-dimensional tensor called a \*scaler.
2. 1-dimensional tensor called a \*vector.
3. Likewise, a 2-dimensional tensor is often referred to as a \*matrix.
4. Anything with more than two dimensions is generally just called a tensor.


**_By default, TensorFlow creates tensors with either an int32 or float32 datatype._**

1. **Scalar**: A scalar is known as a rank 0 tensor. Because it has no dimensions (it's just a number).
   O-dimensional tensor called a \*scaler.


In [6]:
scalar = tf.constant(7)
print(scalar, scalar.ndim)  # ndim=0

tf.Tensor(7, shape=(), dtype=int32) 0


2. Vector: 1 dimentional


In [8]:
# one dimentinal
vector = tf.constant([12, 13])
print(vector, vector.ndim)  # ndim=1

tf.Tensor([12 13], shape=(2,), dtype=int32) 1


3. Matrix: more than 1 dimentional(normaly 2 dimention).


In [10]:
# matrix: more than 1 dimentional(normaly 2 dimention)
matrix = tf.constant([[12, 13], [13, 14]])
print(matrix, matrix.ndim)

tf.Tensor(
[[12 13]
 [13 14]], shape=(2, 2), dtype=int32) 2


In [12]:
# another matrix
matrix_two = tf.constant([[10.0, 7.0], [3.0, 2.0], [8.0, 9.0]], dtype=tf.float16)
print(matrix_two, matrix_two.ndim)  # ndim=2

tf.Tensor(
[[10.  7.]
 [ 3.  2.]
 [ 8.  9.]], shape=(3, 2), dtype=float16) 2


4. Tensor: A tensor can have an arbitrary (unlimited) amount of dimensions.

        For example, you might turn a series of images into tensors with shape (224, 224, 3, 32), where:
- 224, 224 (the first 2 dimensions) are the height and width of the images in pixels.
- 3 is the number of colour channels of the image (red, green blue).
- 32 is the batch size (the number of images a neural network sees at any one time).


In [22]:
tensor = tf.constant(
    [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]]
)
print(tensor, tensor.ndim, tf.size(tensor)) # 3 dimentional or rank=3

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32) 3 tf.Tensor(18, shape=(), dtype=int32)


##### tf.Variable():
The difference between `tf.Variable()` and `tf.constant()` is tensors created with `tf.constant()` are immutable (can't be changed, can only be used to create a new tensor), where as, tensors created with `tf.Variable()` are mutable (can be changed).

In [23]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [24]:
## changing value using assign()
changeable_tensor[0].assign(7) # 10 will be 7
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [27]:
# Will error (can't change tf.constant())
# unchangeable_tensor[0].assign(7)
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

## 2. Getting Information
1. Shape: The length (number of elements) of each of the dimensions of a tensor.
2. Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
3. Axis or Dimension: A particular dimension of a tensor.
4. Size: The total number of items in the tensor.

In [31]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
print(rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor))

(2, 3, 4, 5) 4 tf.Tensor(120, shape=(), dtype=int32)


In [34]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


## 3. TensorFlow Random:

1. **tf.random.uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None)**: generates a tensor with values drawn from a uniform distribution. You specify the shape of the output tensor, along with optional arguments such as minval (minimum value) and maxval (maximum value).

2. **tf.random.normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None)**: generates a tensor with values drawn from a normal (Gaussian) distribution.

3. **tf.random.truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None)**: generates a tensor with values drawn from a truncated normal distribution. The distribution is similar to the normal distribution, but any values more than two standard deviations from the mean are discarded and redrawn.

4. **tf.random.shuffle(value, seed=None)**: This function shuffles the elements of a tensor along its first dimension. It is commonly used for randomizing the order of training data samples.

5. **tf.random.set_seed(seed)**: It ensures that the random operations produce deterministic results across runs when using the same seed.
