# TensorFlow:
<a id='h_cell'></a>

TensorFlow is an open-source end-to-end machine learning library for preprocessing data, modelling data and serving models.

|#NO|Topic|Status|
|--:|:---          |--:|
|01| [Terminology](#ter_cell)||
|02| [Getting information](#gi_cell)|
|03| [***Tensor Random***](#random_cell)|
|04| [***Create Tensor***](#ctensor_cell)|
|05| [Tensor Data Type](#dtype_cell)|
|06| [***Math and Logic with Tensorflow***](#math_cell)|
|07| [***Manipulating Tensor Shape or Braodcasting***](#mts_cell)|
|08| [***Array Accessing***](#aa_cell)|
|09| [***Frequently used method***](#im_cell)|
|09| [***Finding access to GPUs***](#gpu_cell)|


In [1]:
import tensorflow as tf

print(tf.__version__)

2.12.0


### [1. Terminology](#h_cell)
<a id='ter_cell'></a>

A brief note about tensors and their number of dimensions, and terminology:

1. O-dimensional tensor called a \*scaler.
2. 1-dimensional tensor called a \*vector.
3. Likewise, a 2-dimensional tensor is often referred to as a \*matrix.
4. Anything with more than two dimensions is generally just called a tensor.

**_By default, TensorFlow creates tensors with either an int32 or float32 datatype._**

1. **Scalar**: A scalar is known as a rank 0 tensor. Because it has no dimensions (it's just a number).
   O-dimensional tensor called a **scaler**.


In [2]:
scalar = tf.constant(7)
print(scalar, scalar.ndim)  # ndim=0

tf.Tensor(7, shape=(), dtype=int32) 0


2. Vector: 1 dimentional


In [3]:
# one dimentinal
vector = tf.constant([12, 13])
print(vector, vector.ndim)  # ndim=1

tf.Tensor([12 13], shape=(2,), dtype=int32) 1


3. Matrix: more than 1 dimentional(normaly 2 dimention).


In [4]:
# matrix: more than 1 dimentional(normaly 2 dimention)
matrix = tf.constant([[12, 13], [13, 14]])
print(matrix, matrix.ndim)

tf.Tensor(
[[12 13]
 [13 14]], shape=(2, 2), dtype=int32) 2


In [5]:
# another matrix
matrix_two = tf.constant([[10.0, 7.0], [3.0, 2.0], [8.0, 9.0]], dtype=tf.float16)
print(matrix_two, matrix_two.ndim)  # ndim=2

tf.Tensor(
[[10.  7.]
 [ 3.  2.]
 [ 8.  9.]], shape=(3, 2), dtype=float16) 2


4.  Tensor: A tensor can have an arbitrary (unlimited) amount of dimensions.

        For example, you might turn a series of images into tensors with shape (224, 224, 3, 32), where:

- 224, 224 (the first 2 dimensions) are the height and width of the images in pixels.
- 3 is the number of colour channels of the image (red, green blue).
- 32 is the batch size (the number of images a neural network sees at any one time).


In [3]:
tensor = tf.constant(
    [[[1, 2, 3,4], [4, 5, 6,4]], [[7, 8, 9,4], [10, 11, 12,4]], [[13, 14, 15,4], [16, 17, 18,4]]]
)
print(tensor, tensor.ndim, tf.size(tensor))  # 3 dimentional or rank=3

tf.Tensor(
[[[ 1  2  3  4]
  [ 4  5  6  4]]

 [[ 7  8  9  4]
  [10 11 12  4]]

 [[13 14 15  4]
  [16 17 18  4]]], shape=(3, 2, 4), dtype=int32) 3 tf.Tensor(24, shape=(), dtype=int32)


##### tf.Variable():

The difference between `tf.Variable()` and `tf.constant()` is tensors created with `tf.constant()` are immutable (can't be changed, can only be used to create a new tensor), where as, tensors created with `tf.Variable()` are mutable (can be changed).


In [7]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [8]:
## changing value using assign()
changeable_tensor[0].assign(7)  # 10 will be 7
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [9]:
# Will error (can't change tf.constant())
# unchangeable_tensor[0].assign(7)
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

## [2. Getting Information](#h_cell)
<a id='gi_cell'></a>

1. Shape: The length (number of elements) of each of the dimensions of a tensor.
2. Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
3. Axis or Dimension: A particular dimension of a tensor.
4. Size: The total number of items in the tensor.


In [10]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
print(rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor))

(2, 3, 4, 5) 4 tf.Tensor(120, shape=(), dtype=int32)


In [11]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print(
    "Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()
)  # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [13]:
# access like python list
rank_4_tensor[:2, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [14]:
rank_2_tensor = tf.constant([[10, 7], [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

**_Add new axis:_**

1. `tf.newaxis`
2. `tf.expand_dims()`


In [15]:
rank_3_tensor = rank_2_tensor[
    ..., tf.newaxis
]  # in Python "..." means "all dimensions prior to"
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]])>)

In [16]:
tf.expand_dims(rank_2_tensor, axis=-1)  # "-1" means last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

## [3. TensorFlow Random:](#h_cell)
<a id='random_cell'></a>

1. **`tf.random.uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None)`**: generates a tensor with values drawn from a uniform distribution. You specify the shape of the output tensor, along with optional arguments such as minval (minimum value) and maxval (maximum value).

2. **`tf.random.normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None)`**: generates a tensor with values drawn from a normal (Gaussian) distribution.

3. **`tf.random.truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None)`**: generates a tensor with values drawn from a truncated normal distribution. The distribution is similar to the normal distribution, but any values more than two standard deviations from the mean are discarded and redrawn.

4. **`tf.random.shuffle(value, seed=None)`**: This function shuffles the elements of a tensor along its first dimension. It is commonly used for randomizing the order of training data samples.

5. **`tf.random.set_seed(seed)`**: It ensures that the random operations produce deterministic results across runs when using the same seed.


1. `tf.random.uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None)`


In [4]:
tf.random.uniform((2, 3), maxval=5, dtype=tf.int32)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 0, 4],
       [3, 0, 1]])>

2. `tf.random.normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None)`


In [11]:
tf.random.normal((2, 3), mean=0, dtype=tf.float32)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.33875433,  0.3449861 , -0.6605785 ],
       [-0.2854994 ,  0.43852386,  0.8288566 ]], dtype=float32)>

3. `tf.random.truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None)`


In [12]:
tf.random.truncated_normal((3, 4), mean=0.0, stddev=1.0, dtype=tf.float32, seed=None)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.61346006, -1.0256168 , -1.1752816 , -0.79817134],
       [ 1.2787406 ,  0.3146979 ,  0.6080974 ,  0.5469729 ],
       [-0.04225652, -0.57318485, -0.09746004,  1.3598968 ]],
      dtype=float32)>

4. `tf.random.shuffle(value, seed=None)`


In [18]:
not_shuffled = tf.constant([[10, 7], [3, 4], [2, 5]])
# Gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

5. `tf.random.set_seed(seed)`


In [21]:
tf.random.set_seed(123)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]])>

In [8]:
tf.random.set_seed(123)
tf_random_seed = tf.random.normal((2, 3, 3), dtype=tf.float16)
tf_random_seed.shape, tf_random_seed.ndim, tf_random_seed, tf_random_seed[0][
    0
], tf_random_seed[1][1][2]

(TensorShape([2, 3, 3]),
 3,
 <tf.Tensor: shape=(2, 3, 3), dtype=float16, numpy=
 array([[[-0.898  , -1.826  , -0.4443 ],
         [-1.488  , -0.7856 ,  0.1962 ],
         [ 0.176  , -1.525  ,  0.6353 ]],
 
        [[ 0.668  ,  1.423  ,  0.04562],
         [-0.2169 , -1.708  ,  0.5176 ],
         [-0.11975, -1.062  , -0.541  ]]], dtype=float16)>,
 <tf.Tensor: shape=(3,), dtype=float16, numpy=array([-0.898 , -1.826 , -0.4443], dtype=float16)>,
 <tf.Tensor: shape=(), dtype=float16, numpy=0.5176>)

## [4. Create tensor:](#h_cell)
<a id='ctensor_cell'></a>

1. `tf.zeros()`
2. `tf.ones()`


In [23]:
zeros_tensor = tf.zeros(shape=(2, 3))
ones_tensor = tf.ones(shape=(3, 2))
zeros_tensor, ones_tensor

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[0., 0., 0.],
        [0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>)

3. using numpy:

In [24]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.constant(numpy_A,  
                shape=[2, 4, 3]) # note: the shape total (2*4*3) has to match the number of elements in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]])>)

## [5. Tensor Data type:](#h_cell)
<a id='dtype_cell'></a>

1. Changing Data Type: `tf.cast(tensor, dtype= tf.float16)`
   - `tf.ffloat16`: will reduce precision.


In [58]:
B = tf.constant([1.7, 7.4])
print(B)
B = tf.cast(B, dtype=tf.float16)
B

tf.Tensor([1.7 7.4], shape=(2,), dtype=float32)


<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

## [6. Math and Logic with Tensorflow](#h_cell)
<a id='math_cell'></a>


1. Basic Operation


In [21]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10, tensor, tensor * 10, tensor - 10, tf.multiply(tensor, 10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]])>)

### 6.1 Matrix Multiplication:

Tensorflow implements matrix multiplication functionality in the `tf.matmul()` method.

1.  The inner dimensions must match:

        (3, 2) @ (3, 2) won't work
        (2, 3) @ (3, 2) will work
        (3, 2) @ (2, 3) will work

2.  The resulting matrix has the shape of the outer dimensions:

        (2, 3) @ (3, 2) -> (2, 2)
        (3, 2) @ (2, 3) -> (3, 3)

### 6.2 Element wise multiplication:

PyTorch implements multiplication functionality in the `torch.mul()` or `*` method.

        (3, 2) @ (2, 3) won't work
        (2, 3) @ (3, 3) will work
$$[m\times n\times o] * [p\times q\times r]=[m\times n\times o]\text{ this will be the new shape}$$
* Each tensor must have at least one dimension - no empty tensors.
* Comparing the dimension sizes of the two tensors, **going from last to first:**
    * Each dimension must be equal $m=p\;, n=q,\; o=r $, **or**
    * One of the dimensions must be of size 1, $p=1\;, q=1,\; o=r=1 $**or**
    * The dimension does not exist in one of the tensors $q=1,\; o=r=1 $


In [13]:
a=tf.Variable([[1, 1, 2],
        [2, 2, 2]])
b=tf.Variable([[1, 1, 1]])
a.shape, a*a, a*b

(TensorShape([2, 3]),
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 1, 4],
        [4, 4, 4]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 1, 2],
        [2, 2, 2]])>)

In [27]:
tensor = tf.constant([[10, 7], [3, 4]])
print(tensor.shape, tensor.ndim)
element_wise_mul = (
    tensor * tensor
)  # Element wise multiplication: [1*1, 2*2, 3*3]=[1, 4, 9]
print("Element-Wise-Multiplication", element_wise_mul)
print("Element-Wise-Multiplication: tf.multiply", tf.multiply(tensor, tensor))

print("Matrix-Multiplication:", tf.matmul(tensor, tensor))

(2, 2) 2
Element-Wise-Multiplication tf.Tensor(
[[100  49]
 [  9  16]], shape=(2, 2), dtype=int32)
Element-Wise-Multiplication: tf.multiply tf.Tensor(
[[100  49]
 [  9  16]], shape=(2, 2), dtype=int32)
Matrix-Multiplication: tf.Tensor(
[[121  98]
 [ 42  37]], shape=(2, 2), dtype=int32)


In [55]:
# Create (3, 2) tensor
X = tf.constant([[1, 2], [3, 4], [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8], [9, 10], [11, 12]])
print(X.shape, Y.shape, X * Y)
print(tf.matmul(X, tf.reshape(Y, (2, 3))), tf.matmul(X, tf.transpose(Y)))
print(tf.tensordot(X, tf.transpose(Y), axes=2))

(3, 2) (3, 2) tf.Tensor(
[[ 7 16]
 [27 40]
 [55 72]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]], shape=(3, 3), dtype=int32) tf.Tensor(
[[ 23  29  35]
 [ 53  67  81]
 [ 83 105 127]], shape=(3, 3), dtype=int32)
tf.Tensor(212, shape=(), dtype=int32)


the outputs of tf.reshape() and tf.transpose() when called on Y, even though they have the same shape, are different. because

- `tf.reshape():`- change the shape of the given tensor (first) and then insert values in order they appear (in our case, 7, 8, 9, 10, 11, 12).
- `tf.transpose():`- swap the axis.


In [45]:
Y = tf.constant([[7, 8], [9, 10], [11, 12]])
print(Y.shape, tf.reshape(Y, (2, 3)).shape, tf.transpose(Y).shape)
Y, tf.reshape(Y, (2, 3)), tf.transpose(Y)

(3, 2) (2, 3) (2, 3)


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]])>)

In [39]:
tf.matmul(a=X, b=Y, transpose_a=False, transpose_b=True)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

### More Math:

1. `tf.abs(x)`:
1. `tf.reduce_min(x)`:
1. `tf.reduce_max(x)`:
1. `tf.reduce_mean(x)`:
1. `tf.sum(x)`:

**Note:** typically, each of these is under the math module, e.g. `tf.math.reduce_min()` but you can use the alias `tf.reduce_min()`.


In [59]:
import numpy as np

E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([23, 17, 90, 68, 43, 14, 90, 54,  5, 88, 95, 35, 66, 18, 75, 42, 94,
       12, 28, 98, 87, 96, 52,  0, 49, 66, 77, 16, 15, 24, 84, 91, 35, 11,
       86, 84, 74, 79, 68, 79, 78, 96, 18, 17, 96, 45, 82,  5, 96, 17])>

In [64]:
print(f"tf.reduce_min(E) = {tf.reduce_min(E)}")
print(f"tf.reduce_max(E) = {tf.reduce_max(E)} ")
print(f"tf.argmax(E).numpy()={tf.argmax(E).numpy()}")
# tf.argmax(F).numy() return the index
print(f"tf.reduce_mean(E) = {tf.reduce_mean(E)}")
print(f"tf.reduce_sum(E) = {tf.reduce_sum(E)}")

tf.reduce_min(E) = 0
tf.reduce_max(E) = 98 
tf.argmax(E).numpy()=19
tf.reduce_mean(E) = 55
tf.reduce_sum(E) = 2778


1. `tf.square()` - get the square of every value in a tensor.
2. `tf.sqrt()` - get the squareroot of every value in a tensor (note: the elements need to be floats or this will error).
3. `tf.math.log()` - get the natural log of every value in a tensor (elements need to floats).


In [65]:
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [69]:
print(f"tf.square(H)= {tf.square(H)}")
print(
    f"tf.sqrt(H)= {tf.sqrt(tf.cast(H, dtype= tf.float32))}"
)  # with out casting it will raise an error
print(f"tf.math.log(H)= {tf.math.log(tf.cast(H, dtype= tf.float32))}")

tf.square(H)= [ 1  4  9 16 25 36 49 64 81]
tf.sqrt(H)= [1.        1.4142135 1.7320508 2.        2.236068  2.4494898 2.6457512
 2.828427  3.       ]
tf.math.log(H)= [0.        0.6931472 1.0986123 1.3862944 1.609438  1.7917595 1.9459102
 2.0794415 2.1972246]


## [7. Manipulating Tensor Shapes](#h_cell)
<a id='mts_cell'></a>

1. `x.assign()`:
2. `x.assign_add()`:
3. `tf.reshape(x, (shape))`:
4. `tf.transpose()`:
5. `tf.squeeze()`: removing all single dimensions.
6. `tf.one_hot(x, depth=4, on_value=?, off_value=?)`: would like to one-hot encode it.


In [75]:
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [76]:
# Squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

In [73]:
## one_hot(x, depth, on_value=?, off_value=?)
some_list = [0, 1, 2, 3]
tf.one_hot(some_list, depth=len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [74]:
tf.one_hot(some_list, depth=len(some_list), off_value="off", on_value="on")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'on', b'off', b'off', b'off'],
       [b'off', b'on', b'off', b'off'],
       [b'off', b'off', b'on', b'off'],
       [b'off', b'off', b'off', b'on']], dtype=object)>

`@tf.function`: It turns a Python function into a callable TensorFlow graph. ensorFlow will attempt to convert it into a fast(er) version of itself (by making it part of a computation graph).


In [79]:
def function(x, y):
    return x**2 + y


x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [78]:
@tf.function
def tf_function(x, y):
    return x**2 + y


tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

One of the main ones being potential code speed-ups where possible.


## [8. Tensor Accessing:](#h_cell)
<a id='aa_cell'></a>

## [9. Frequently used method:](#h_cell)
<a id='im_cell'></a>

## [10. Finding access to GPUs](#h_cell)
<a id='gpu_cell'></a>

In [29]:
print(tf.config.list_physical_devices('CPU'))
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
[]
