#### Python slicing:

In python index start with 0 like other programming language. However, For negative index, it will start from `-1 to -n`. For example, arr[0:3] will print 0 to 2 index elements.
`Lst[ Initial : End : IndexJump ]`

- **_Initial:_** Starting index.
- **_End:_** Ending Index.
- **_IndexJump:_** How many elemnts it will skip.

| Index     |   0 |   1 |   2 |   3 |   4 |
| :-------- | --: | --: | --: | --: | --: |
| Elememnts |   1 |   2 |   3 |   4 |   5 |
| Neg-Index |  -5 |  -4 |  -3 |  -2 |  -1 |


In [17]:
arr = [12, 13, 14, 15, 16]
print(arr[1:-2])
print(arr[-4:-2])
print(arr[:-1])

[13, 14]
[13, 14]
[12, 13, 14, 15]


slicing on multi-dimensional arrays (e.g., 2D arrays) by specifying slices for each dimension separated by commas:


In [13]:
import numpy as np

arr_2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(arr_2d[1:2, 1:-1])

[[4]]


In [73]:
# Create a 2D array (3 rows, 4 columns)
arr = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ])

print("Axis=0->", np.sum(arr, axis=0)) # # Calculate the sum along the rows (axis=0) for each column.
print("Axis=-1->", np.sum(arr, axis=-1)) # #Calculate the sum along the columns (axis=1) for each row. Sum along axis=1 (columns)

m,n = arr.shape
# print(m,n)
l=[]
k=[]

for i in range(n):
    sum = 0
    for j in range(m):
        sum+=arr[j][i]
    k.append(sum)
print("Axis(0):",k)

for i in range(m):
    sum = 0
    for j in range(n):
        sum+=arr[i][j]
    l.append(sum)
print("Axis(1 or -1):",l)

Axis=0-> [15 18 21 24]
Axis=-1-> [10 26 42]
Axis(0): [15, 18, 21, 24]
Axis(1 or -1): [10, 26, 42]


In [26]:
## 2d array:
# Sample 2D tensor (3 rows, 4 columns) representing a batch of data
input_data = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Calculate the sum along the rows (axis=0) for each column
print("Axis = 0->", np.sum(input_data, axis=0))  # output: [15, 18, 21, 24]
# Calculate the sum along the columns (axis=1) for each row
print("Axis = 1->", np.sum(input_data, axis=1))  # output:[10,26,42]
# Axis=-1 ->calculate the sum along the last axis,
print("Axis = -1->", np.sum(input_data, axis=-1))  # output:[10,26,42]

Axis = 0-> [15 18 21 24]
Axis = 1-> [10 26 42]
Axis = -1-> [10 26 42]


In [36]:
arr = np.array(
    [
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
    ]
)
print(arr[1:,1:,1:])
print(arr[0][0][0])

[[[18 19 20]
  [22 23 24]]]
1


In [119]:
arr = np.array(
    [
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
    ]
)
# Calculate the sum along the rows (axis=0) for each column
print("Axis = 0->\n", np.sum(arr, axis=0))  # output: [15, 18, 21, 24]
# Calculate the sum along the columns (axis=1) for each row
print("Axis = 1->\n", np.sum(arr, axis=1))  # output:[10,26,42]
# Axis=-1 ->calculate the sum along the last axis,
print("Axis = -1->\n", np.sum(arr, axis=-1))  # output:[10,26,42]
print(arr.shape)
m,n,l=arr.shape
axis_2=np.zeros([m,n])
for i in range(m):
    for j in range(n):
        sum = 0
        for k in range(l):
            sum+=arr[i][j][k]
        axis_2[i][j]=sum
print("axis=-1 or 2->\n",axis_2)

axis_1= np.zeros([m,l])
for i in range(m):
    for j in range(l):
        sum = 0
        for k in range(n):
            sum+=arr[i][k][j]
        axis_1[i][j]=sum
print("axis=1->\n", axis_1)

axis_0=np.zeros([n,l])
for i in range(n):
    for j in range(l):
        sum = 0
        for k in range(m):
            sum+=arr[k][i][j]
        axis_0[i][j]=sum
print("axis=0 ->\n",axis_0)


Axis = 0->
 [[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]
Axis = 1->
 [[15 18 21 24]
 [51 54 57 60]]
Axis = -1->
 [[10 26 42]
 [58 74 90]]
(2, 3, 4)
axis=-1 or 2->
 [[10. 26. 42.]
 [58. 74. 90.]]
axis=1->
 [[15. 18. 21. 24.]
 [51. 54. 57. 60.]]
axis=0 ->
 [[14. 16. 18. 20.]
 [22. 24. 26. 28.]
 [30. 32. 34. 36.]]


In [3]:
import os


current_dir= os.getcwd()
print("Get Current Working Directory", os.getcwd())
# print("Absolute Path:",os.path.abspath(__file__))
# print("Absolute Path Directory:",os.path.dirname(os.path.abspath(__file__)))
print(os.path.join(os.getcwd(),"path"))

Get Current Working Directory g:\Code\deep-learning-libray\notes
g:\Code\deep-learning-libray\notes\path
