In [36]:
import numpy as np
import math

# Numpy:
1. Terminology
2. Getting information
3. Random

## 1. Terminology
A brief note about Numpy and their number of dimensions, and terminology:
1. O-dimensional tensor called a *scaler*.
2. 1-dimensional tensor called a *vector*.
3. Likewise, a 2-dimensional tensor is often referred to as a *matrix.*
4. Anything with more than two dimensions is generally just called a multi dimentional numpy array or tensor.

1. Scaler:

In [56]:
scaler= np.random.rand(1)
scaler.ndim, scaler.shape, scaler.item(), scaler, type(scaler), scaler

(1,
 (1,),
 0.2793621769098912,
 array([0.27936218]),
 numpy.ndarray,
 array([0.27936218]))

2. **Vector:** Algebraically, a vector is a collection of coordinates of a point in space. Thus, a vector with two values represents a point in a 2-dimensional space. In Computer Science, a vector is an arrangement of numbers along a single dimension. It is also commonly known as an array or a list or a tuple.

In [58]:
vector= np.array([7,8])
print(type(vector), vector, vector.ndim, vector.shape)

<class 'numpy.ndarray'> [7 8] 1 (2,)


3. **Matrix: 2 dimentional**

In [59]:
## Matrix
MATRIX=np.array([[7, 8], 
                    [9, 10]])
print(type(MATRIX))
MATRIX,MATRIX.shape, MATRIX.ndim,MATRIX.dtype

<class 'numpy.ndarray'>


(array([[ 7,  8],
        [ 9, 10]]),
 (2, 2),
 2,
 dtype('int64'))

4. **Tensor or Multi-dimentional:**

In [61]:
# Tensor
TENSOR = np.array([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR, TENSOR.shape, TENSOR.ndim, type(TENSOR)

(array([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]]),
 (1, 3, 3),
 3,
 numpy.ndarray)

## 2. Getting Information:
        1. type(x): type(tensor) will return the type of the numpy object.
        2. x.dtype: tensor.dtype will give you the data type.
        3. x.shape: tensor.shape will give you the shape of the numpy object.
        4. x.size: tensor.size will give you the total number of elements.
        5. x.ndim: The ndim attribute of a PyTorch tensor returns the number of dimensions (rank) of the object.

In [62]:
# Create a NumPy array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Get type of the array
print(type(array))

# Get data type of the array
print(array.dtype)

# Get shape of the array
print(array.shape)

# Get total number of elements in the array
print(array.size)

# Get number of dimensions of the array
print(array.ndim)

# Get name of the data type
print(array.dtype.name)

<class 'numpy.ndarray'>
int64
(2, 3)
6
2
int64


In [63]:
vector= np.array([7,8])
print(type(vector), vector, vector.ndim, vector.shape)
matrix_1=np.array([[1,2],[2,3], [4,5]])
print("Matrix Info: ",type(matrix_1), matrix_1, matrix_1.ndim, matrix_1.shape)
matrix_2= np.random.rand(3,2,5)
print("Matrix-2 Info: ",type(matrix_2),"\n", matrix_2, matrix_2.ndim, matrix_2.shape)

<class 'numpy.ndarray'> [7 8] 1 (2,)
Matrix Info:  <class 'numpy.ndarray'> [[1 2]
 [2 3]
 [4 5]] 2 (3, 2)
Matrix-2 Info:  <class 'numpy.ndarray'> 
 [[[0.96103763 0.09813216 0.40699555 0.00837645 0.56805893]
  [0.57660977 0.13714426 0.67221857 0.14287373 0.5092315 ]]

 [[0.36876195 0.24910739 0.13628212 0.11929113 0.05238813]
  [0.43489931 0.77070538 0.85091418 0.62128267 0.37988769]]

 [[0.67991104 0.3137655  0.72663798 0.91448319 0.09489548]
  [0.66497695 0.35687279 0.76229092 0.94500569 0.2237422 ]]] 3 (3, 2, 5)


**Note:** 

1. $shape=(2,)$ means that a 1-D arrray and index 0 has 2 elements.
1. $shape=(3,2,5)$ means that a 2-D arrray and index[0] has 3 elements and index[1] has 2 elements and index[2] has 5 elements.

## 3. numpy.random():
This module contains the functions which are used for generating random numbers.

Methods:

1. `np.random.rand(d0, d1, ..., dn)`: This function of random module is used to generate random numbers or values in a given shape.
2. `np.random.randn(d0, d1, ..., dn)`: This function of random module return a sample from the ***standard normal*** distribution.
3. `np.random.randint(low, high=None, size=None, dtype=int)`: generate random integers from inclusive(low) to exclusive(high).
4. `np.random.random_integers(low, high=None, size=None)`: generate random integers number of type np.int between low and high.
5. `numpy.random.uniform(low=0.0, high=1.0, size=None)`:  generate random floating-point numbers within a specified range.
6. `numpy.random.choice(a, size=None, replace=True, p=None)`: Generates a random sample from a given 1-D array.
7. `numpy.random.normal(loc=0.0, scale=1.0, size=None)`: Draw random samples from a normal (Gaussian) distribution.
8. `numpy.random.shuffle(x):` reorder the elements.

### Creating array:
1. np.random.rand(d0, d1, ...dn)
2. np.random

In [25]:
np.random.seed(100)
a= np.random.randn(2,3,4)
a, a.shape, a.ndim, a[1], a[0]

(array([[[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
         [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
         [-0.18949583,  0.25500144, -0.45802699,  0.43516349]],
 
        [[-0.58359505,  0.81684707,  0.67272081, -0.10441114],
         [-0.53128038,  1.02973269, -0.43813562, -1.11831825],
         [ 1.61898166,  1.54160517, -0.25187914, -0.84243574]]]),
 (2, 3, 4),
 3,
 array([[-0.58359505,  0.81684707,  0.67272081, -0.10441114],
        [-0.53128038,  1.02973269, -0.43813562, -1.11831825],
        [ 1.61898166,  1.54160517, -0.25187914, -0.84243574]]),
 array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
        [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
        [-0.18949583,  0.25500144, -0.45802699,  0.43516349]]))

### Multiplication Rule:

In [26]:
import numpy as np

In [35]:
a= np.random.rand(2,3,3)
b= np.random.rand(1,3)
print("A: ", a, a.shape, a.ndim)
print("B: ", b, b.shape, b.ndim)
print("a*b=",a*b)
print("np.matmul(a,b)=",np.matmul(a,b.T))
print("b-Shape:",b.shape,"after transpose:", b.T.shape)

A:  [[[0.29943802 0.85689553 0.47298399]
  [0.66327705 0.80572861 0.2529805 ]
  [0.07957344 0.73276061 0.96139748]]

 [[0.95380473 0.49049905 0.63219206]
  [0.73299502 0.9024095  0.16224692]
  [0.40588132 0.41709074 0.69559103]]] (2, 3, 3) 3
B:  [[0.42484724 0.85811423 0.84693248]] (1, 3) 2
a*b= [[[0.12721542 0.73531424 0.4005855 ]
  [0.28179142 0.69140718 0.21425741]
  [0.03380656 0.6287923  0.81423875]]

 [[0.40522131 0.42090421 0.53542399]
  [0.31141091 0.77437043 0.13741219]
  [0.17243756 0.35791149 0.58911863]]]
np.matmul(a,b)= [[[1.26311516]
  [1.18745601]
  [1.4768376 ]]

 [[1.36154951]
  [1.22319353]
  [1.11946769]]]
b-Shape: (1, 3) after transpose: (3, 1)
