In [24]:
import numpy as np
import math

# Numpy:
1. Terminology
2. Getting information
3. Random
4. Create Numpy
5. Numpy Data Type
6. Math and Logic Numpy

## 1. Terminology
A brief note about Numpy and their number of dimensions, and terminology:
1. O-dimensional tensor called a *scaler*.
2. 1-dimensional tensor called a *vector*.
3. Likewise, a 2-dimensional tensor is often referred to as a *matrix.*
4. Anything with more than two dimensions is generally just called a multi dimentional numpy array or tensor.

1. Scaler:

In [56]:
scaler= np.random.rand(1)
scaler.ndim, scaler.shape, scaler.item(), scaler, type(scaler), scaler

(1,
 (1,),
 0.2793621769098912,
 array([0.27936218]),
 numpy.ndarray,
 array([0.27936218]))

2. **Vector:** Algebraically, a vector is a collection of coordinates of a point in space. Thus, a vector with two values represents a point in a 2-dimensional space. In Computer Science, a vector is an arrangement of numbers along a single dimension. It is also commonly known as an array or a list or a tuple.

In [58]:
vector= np.array([7,8])
print(type(vector), vector, vector.ndim, vector.shape)

<class 'numpy.ndarray'> [7 8] 1 (2,)


3. **Matrix: 2 dimentional**

In [59]:
## Matrix
MATRIX=np.array([[7, 8], 
                    [9, 10]])
print(type(MATRIX))
MATRIX,MATRIX.shape, MATRIX.ndim,MATRIX.dtype

<class 'numpy.ndarray'>


(array([[ 7,  8],
        [ 9, 10]]),
 (2, 2),
 2,
 dtype('int64'))

4. **Tensor or Multi-dimentional:**

In [61]:
# Tensor
TENSOR = np.array([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR, TENSOR.shape, TENSOR.ndim, type(TENSOR)

(array([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]]),
 (1, 3, 3),
 3,
 numpy.ndarray)

## 2. Getting Information:
        1. type(x): type(tensor) will return the type of the numpy object.
        2. x.dtype: tensor.dtype will give you the data type.
        3. x.shape: tensor.shape will give you the shape of the numpy object.
        4. x.size: tensor.size will give you the total number of elements.
        5. x.ndim: The ndim attribute of a PyTorch tensor returns the number of dimensions (rank) of the object.

In [62]:
# Create a NumPy array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Get type of the array
print(type(array))

# Get data type of the array
print(array.dtype)

# Get shape of the array
print(array.shape)

# Get total number of elements in the array
print(array.size)

# Get number of dimensions of the array
print(array.ndim)

# Get name of the data type
print(array.dtype.name)

<class 'numpy.ndarray'>
int64
(2, 3)
6
2
int64


In [63]:
vector= np.array([7,8])
print(type(vector), vector, vector.ndim, vector.shape)
matrix_1=np.array([[1,2],[2,3], [4,5]])
print("Matrix Info: ",type(matrix_1), matrix_1, matrix_1.ndim, matrix_1.shape)
matrix_2= np.random.rand(3,2,5)
print("Matrix-2 Info: ",type(matrix_2),"\n", matrix_2, matrix_2.ndim, matrix_2.shape)

<class 'numpy.ndarray'> [7 8] 1 (2,)
Matrix Info:  <class 'numpy.ndarray'> [[1 2]
 [2 3]
 [4 5]] 2 (3, 2)
Matrix-2 Info:  <class 'numpy.ndarray'> 
 [[[0.96103763 0.09813216 0.40699555 0.00837645 0.56805893]
  [0.57660977 0.13714426 0.67221857 0.14287373 0.5092315 ]]

 [[0.36876195 0.24910739 0.13628212 0.11929113 0.05238813]
  [0.43489931 0.77070538 0.85091418 0.62128267 0.37988769]]

 [[0.67991104 0.3137655  0.72663798 0.91448319 0.09489548]
  [0.66497695 0.35687279 0.76229092 0.94500569 0.2237422 ]]] 3 (3, 2, 5)


**Note:** 

1. $shape=(2,)$ means that a 1-D arrray and index 0 has 2 elements.
1. $shape=(3,2,5)$ means that a 2-D arrray and index[0] has 3 elements and index[1] has 2 elements and index[2] has 5 elements.

## 3. numpy.random():
This module contains the functions which are used for generating random numbers.

Methods:

1. `np.random.rand(d0, d1, ..., dn)`: This function of random module is used to generate random numbers or values in a given shape.
2. `np.random.randn(d0, d1, ..., dn)`: This function of random module return a sample from the ***standard normal*** distribution.
3. `np.random.randint(low, high=None, size=None, dtype=int)`: generate random integers from inclusive(low) to exclusive(high).
4. `np.random.random_integers(low, high=None, size=None)`: generate random integers number of type np.int between low and high.
5. `numpy.random.uniform(low=0.0, high=1.0, size=None)`:  generate random floating-point numbers within a specified range.
6. `numpy.random.choice(a, size=None, replace=True, p=None)`: Generates a random sample from a given 1-D array.
7. `numpy.random.normal(loc=0.0, scale=1.0, size=None)`: Draw random samples from a normal (Gaussian) distribution.
8. `numpy.random.shuffle(x):` reorder the elements.

### Creating array:
1. np.random.rand(d0, d1, ...dn)
2. np.random

In [25]:
np.random.seed(100)
a= np.random.randn(2,3,4)
a, a.shape, a.ndim, a[1], a[0]

(array([[[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
         [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
         [-0.18949583,  0.25500144, -0.45802699,  0.43516349]],
 
        [[-0.58359505,  0.81684707,  0.67272081, -0.10441114],
         [-0.53128038,  1.02973269, -0.43813562, -1.11831825],
         [ 1.61898166,  1.54160517, -0.25187914, -0.84243574]]]),
 (2, 3, 4),
 3,
 array([[-0.58359505,  0.81684707,  0.67272081, -0.10441114],
        [-0.53128038,  1.02973269, -0.43813562, -1.11831825],
        [ 1.61898166,  1.54160517, -0.25187914, -0.84243574]]),
 array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
        [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
        [-0.18949583,  0.25500144, -0.45802699,  0.43516349]]))

### Multiplication Rule:

In [26]:
import numpy as np

In [35]:
a= np.random.rand(2,3,3)
b= np.random.rand(1,3)
print("A: ", a, a.shape, a.ndim)
print("B: ", b, b.shape, b.ndim)
print("a*b=",a*b)
print("np.matmul(a,b)=",np.matmul(a,b.T))
print("b-Shape:",b.shape,"after transpose:", b.T.shape)

A:  [[[0.29943802 0.85689553 0.47298399]
  [0.66327705 0.80572861 0.2529805 ]
  [0.07957344 0.73276061 0.96139748]]

 [[0.95380473 0.49049905 0.63219206]
  [0.73299502 0.9024095  0.16224692]
  [0.40588132 0.41709074 0.69559103]]] (2, 3, 3) 3
B:  [[0.42484724 0.85811423 0.84693248]] (1, 3) 2
a*b= [[[0.12721542 0.73531424 0.4005855 ]
  [0.28179142 0.69140718 0.21425741]
  [0.03380656 0.6287923  0.81423875]]

 [[0.40522131 0.42090421 0.53542399]
  [0.31141091 0.77437043 0.13741219]
  [0.17243756 0.35791149 0.58911863]]]
np.matmul(a,b)= [[[1.26311516]
  [1.18745601]
  [1.4768376 ]]

 [[1.36154951]
  [1.22319353]
  [1.11946769]]]
b-Shape: (1, 3) after transpose: (3, 1)


## 4. Create Numpy Array

1. `np.array()`: create a numpy array.
2. `np.random.rand()`: create a random numpy array with given shape.
3. `np.ones((2,3))`: create a tensor with one.
4. `np.zeors()`: create a tensor with $0$
5. `np.arange(start, end, step)`:
6. `np.empty()`: The `np.empty()` call allocates memory for the tensor, but does not initialize it with any values - so what you're seeing is whatever was in memory at the time of allocation.
6. ``np.*_like(x)`: Often, when you're performing operations on two or more tensors, they will need to be of the same *shape* - that is, having the same number of dimensions and the same number of cells in each dimension. For that, we have the `np.*_like()` methods.
    1. `np.empty_like(x):`
    2. `np.zeros_like(x):`
    3. `np.empty_like(x):`

In [17]:
zeros = np.zeros((2, 3))
print(zeros)

ones = np.ones((2, 3))
print(ones)

np.random.seed(1729)
random = np.random.rand(2, 3)
print(random)

x = np.empty((3, 4))
print(type(x))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.2121586  0.25901824 0.42352188]
 [0.71966101 0.69225093 0.72817482]]
<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
# np.arrange():
zero_to_ten = np.arange(start=0, stop=10, step=1, dtype=float)
zero_to_ten.astype(int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
## np.*_like()
x = np.empty((2, 2, 3))
print(x.shape)
print(x)

empty_like_x = np.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = np.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = np.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

(2, 2, 3)
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
(2, 2, 3)
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
(2, 2, 3)
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
(2, 2, 3)
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


## 5. Data Type:

In [28]:
zero_to_ten = np.arange(start=0, stop=10, step=1, dtype=float) # declare a float data type
zero_to_ten.astype(int) # change the data type

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 6. Math and Logical Operations:

In [10]:
ones = np.zeros((2, 2)) + 1 #addition ones.add()
ones=np.add(ones,100)
twos = np.ones((2, 2)) * 2 #multiplication
threes = (np.ones((2, 2)) * 7 - 1) / 2 # complex operation
fours = twos ** 2 # squre
sqrt2s = twos ** 0.5 ## squre root

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

[[101. 101.]
 [101. 101.]]
[[2. 2.]
 [2. 2.]]
[[3. 3.]
 [3. 3.]]
[[4. 4.]
 [4. 4.]]
[[1.41421356 1.41421356]
 [1.41421356 1.41421356]]


### 6.1 Matrix multiplication
PyTorch implements matrix multiplication functionality in the `torch.matmul()` method.

1. The inner dimensions must match:

        (3, 2) @ (3, 2) won't work
        (2, 3) @ (3, 2) will work
        (3, 2) @ (2, 3) will work
2. The resulting matrix has the shape of the outer dimensions:

        (2, 3) @ (3, 2) -> (2, 2)
        (3, 2) @ (2, 3) -> (3, 3)

### 6.2 Element wise multiplication:
PyTorch implements multiplication functionality in the `torch.mul()` or `*` method.

        (3, 2) @ (2, 3) won't work
        (2, 3) @ (3, 3) will work

In [34]:
a = np.array([1, 2, 3])
print(a.shape, a.ndim)
element_wise_mul=a*a # Element wise multiplication: [1*1, 2*2, 3*3]=[1, 4, 9]
print("Element-Wise-Multiplication",element_wise_mul)
print("Element-Wise-Multiplication: np.multiply()",np.multiply(a, a))

print("Matrix-Multiplication:", np.matmul(a, a))
print("Matrix-Multiplication:", np.dot(a, a))

(3,) 1
Element-Wise-Multiplication [1 4 9]
Element-Wise-Multiplication: np.multiply() [1 4 9]
Matrix-Multiplication: 14
Matrix-Multiplication: 14


In [36]:
# Shapes need to be in the right way  
tensor_A = np.array([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=np.float32)

tensor_B = np.array([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=np.float32)
print(f"tensor_A: {tensor_A.shape} \t {tensor_A.ndim}")
print(f"tensor_B: {tensor_B.shape} \t {tensor_B.ndim}")

print("Element wise:",np.multiply(tensor_A, tensor_B))
print("Transpose:",tensor_A.T.shape)

np.matmul(tensor_A.T, tensor_B) 

tensor_A: (3, 2) 	 2
tensor_B: (3, 2) 	 2
Element wise: [[ 7. 20.]
 [24. 44.]
 [45. 72.]]
Transpose: (2, 3)


array([[ 76., 103.],
       [100., 136.]], dtype=float32)

#### Element wise Multiplication:

* Each tensor must have at least one dimension - no empty tensors.
* Comparing the dimension sizes of the two tensors, *going from last to first:*
* * Each dimension must be equal, *or*
* * One of the dimensions must be of size 1, *or*
* * The dimension does not exist in one of the tensors

In [53]:
a = np.ones((4, 3, 2))

b = a * np.random.randn(   2) # 3rd & 2nd dims identical to a, dim 1 absent
print("b:", b[:1])


c = a * np.random.randn( 3, 1) # 3rd dim = 1, 2nd dim identical to a
print("C:",c)

d = a * np.random.randn(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print("d", d)


b: [[[0.42669569 0.3840521 ]
  [0.42669569 0.3840521 ]
  [0.42669569 0.3840521 ]]]
C: [[[-0.91153107 -0.91153107]
  [ 1.33683925  1.33683925]
  [ 0.37326642  0.37326642]]

 [[-0.91153107 -0.91153107]
  [ 1.33683925  1.33683925]
  [ 0.37326642  0.37326642]]

 [[-0.91153107 -0.91153107]
  [ 1.33683925  1.33683925]
  [ 0.37326642  0.37326642]]

 [[-0.91153107 -0.91153107]
  [ 1.33683925  1.33683925]
  [ 0.37326642  0.37326642]]]
d [[[ 0.5604513  -1.05676443]
  [ 0.5604513  -1.05676443]
  [ 0.5604513  -1.05676443]]

 [[ 0.5604513  -1.05676443]
  [ 0.5604513  -1.05676443]
  [ 0.5604513  -1.05676443]]

 [[ 0.5604513  -1.05676443]
  [ 0.5604513  -1.05676443]
  [ 0.5604513  -1.05676443]]

 [[ 0.5604513  -1.05676443]
  [ 0.5604513  -1.05676443]
  [ 0.5604513  -1.05676443]]]


In [57]:
a = np.ones((4, 3, 2))

b = a * np.random.randn(4, 3)    # dimensions must match last-to-first

c = a * np.rand(   2, 3) # both 3rd & 2nd dims different

d = a * np.rand((0, ))   # can't broadcast with an empty tensor

ValueError: operands could not be broadcast together with shapes (4,3,2) (4,3) 