# Numpy:
<a id='h_cell'></a>


|#NO|Topic|Status|
|--:|:---          |--:|
|01| [Terminology](#ter_cell)||
|02| [Getting information](#gi_cell)|
|03| [***Random***](#random_cell)|
|04| [***Create Numpy***](#carray_cell)|
|05| [Numpy Data Type](#dtype_cell)|
|06| [***Math and Logic Numpy***](#math_cell)|
|07| [***Manipulating Shape or Braodcasting***](#mts_cell)|
|08| [***Array Accessing***](#aa_cell)|
|09| [***Frequently used method***](#im_cell)|

In [38]:
import numpy as np
import math

## [1. Terminology](#h_cell)
<a id='ter_cell'></a>
A brief note about Numpy and their number of dimensions, and terminology:
1. O-dimensional tensor called a *scaler*.
2. 1-dimensional tensor called a *vector*.
3. Likewise, a 2-dimensional tensor is often referred to as a *matrix.*
4. Anything with more than two dimensions is generally just called a multi dimentional numpy array or tensor.

1. Scaler:

In [39]:
scaler= np.random.rand(1)
scaler.ndim, scaler.shape, scaler.item(), scaler, type(scaler), scaler

(1,
 (1,),
 0.21969749262499216,
 array([0.21969749]),
 numpy.ndarray,
 array([0.21969749]))

2. **Vector:** Algebraically, a vector is a collection of coordinates of a point in space. Thus, a vector with two values represents a point in a 2-dimensional space. In Computer Science, a vector is an arrangement of numbers along a single dimension. It is also commonly known as an array or a list or a tuple.

In [40]:
vector= np.array([7,8])
print(type(vector), vector, vector.ndim, vector.shape)

<class 'numpy.ndarray'> [7 8] 1 (2,)


3. **Matrix: 2 dimentional**

In [41]:
## Matrix
MATRIX=np.array([[7, 8], 
                    [9, 10]])
print(type(MATRIX))
MATRIX,MATRIX.shape, MATRIX.ndim,MATRIX.dtype

<class 'numpy.ndarray'>


(array([[ 7,  8],
        [ 9, 10]]),
 (2, 2),
 2,
 dtype('int32'))

4. **Tensor or Multi-dimentional:**

In [42]:
# Tensor
TENSOR = np.array([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR, TENSOR.shape, TENSOR.ndim, type(TENSOR)

(array([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]]),
 (1, 3, 3),
 3,
 numpy.ndarray)

In [43]:
tensor=np.array([[[1, 2, 3,4], [4, 5, 6,4]], [[7, 8, 9,4], [10, 11, 12,4]], [[13, 14, 15,4], [16, 17, 18,4]]])
tensor.shape, tensor.ndim, 

((3, 2, 4), 3)

## [2. Getting Information:](#h_cell)
<a id='gi_cell'></a>
1. type(x): type(tensor) will return the type of the numpy object.
2. x.dtype: tensor.dtype will give you the data type.
3. x.shape: tensor.shape will give you the shape of the numpy object.
4. x.size: tensor.size will give you the total number of elements.
5. x.ndim: The ndim attribute of a PyTorch tensor returns the number of dimensions (rank) of the object.

In [44]:
# Create a NumPy array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Get type of the array
print(type(array))

# Get data type of the array
print(array.dtype)

# Get shape of the array
print(array.shape)

# Get total number of elements in the array
print(array.size)

# Get number of dimensions of the array
print(array.ndim)

# Get name of the data type
print(array.dtype.name)

<class 'numpy.ndarray'>
int32
(2, 3)
6
2
int32


In [45]:
vector= np.array([7,8])
print(type(vector), vector, vector.ndim, vector.shape)
matrix_1=np.array([[1,2],[2,3], [4,5]])
print("Matrix Info: ",type(matrix_1), matrix_1, matrix_1.ndim, matrix_1.shape)
matrix_2= np.random.rand(3,2,5)
print("Matrix-2 Info: ",type(matrix_2),"\n", matrix_2, matrix_2.ndim, matrix_2.shape)

<class 'numpy.ndarray'> [7 8] 1 (2,)
Matrix Info:  <class 'numpy.ndarray'> [[1 2]
 [2 3]
 [4 5]] 2 (3, 2)
Matrix-2 Info:  <class 'numpy.ndarray'> 
 [[[0.97862378 0.81168315 0.17194101 0.81622475 0.27407375]
  [0.43170418 0.94002982 0.81764938 0.33611195 0.17541045]]

 [[0.37283205 0.00568851 0.25242635 0.79566251 0.01525497]
  [0.59884338 0.60380454 0.10514769 0.38194344 0.03647606]]

 [[0.89041156 0.98092086 0.05994199 0.89054594 0.5769015 ]
  [0.74247969 0.63018394 0.58184219 0.02043913 0.21002658]]] 3 (3, 2, 5)


**Note:** 

1. $shape=(2,)$ means that a 1-D arrray and index 0 has 2 elements.
1. $shape=(3,2,5)$ means that a 2-D arrray and index[0] has 3 elements and index[1] has 2 elements and index[2] has 5 elements.

## [3. numpy.random():](#h_cell)
<a id='random_cell'></a>
This module contains the functions which are used for generating random numbers.

Methods:

1. `np.random.rand(d0, d1, ..., dn)`: This function of random module is used to generate random numbers or values in a given shape.
2. `np.random.randn(d0, d1, ..., dn)`: This function of random module return a sample from the ***standard normal*** distribution.
3. `np.random.randint(low, high=None, size=None, dtype=int)`: generate random integers from inclusive(low) to exclusive(high).
4. `np.random.random_integers(low, high=None, size=None)`: generate random integers number of type np.int between low and high.
5. `numpy.random.uniform(low=0.0, high=1.0, size=None)`:  generate random floating-point numbers within a specified range.
6. `numpy.random.choice(a, size=None, replace=True, p=None)`: Generates a random sample from a given 1-D array.
7. `numpy.random.normal(loc=0.0, scale=1.0, size=None)`: Draw random samples from a normal (Gaussian) distribution.
8. `numpy.random.shuffle(x):` reorder the elements.

### Creating array:
1. np.random.rand(d0, d1, ...dn)
2. np.random

In [46]:
## np.random.rand
x= np.random.randint(2,50,(3,3))
x_ran_choice= np.random.choice(2,100,50)
print(x.shape,"\n",x)
print(f"x_ran_choice:{x_ran_choice}")

(3, 3) 
 [[21 16  2]
 [15 14 44]
 [ 5  8  5]]
x_ran_choice:[0 1 0 1 0 1 0 1 1 0 0 1 0 1 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 0 1 0 1 1
 0 0 0 0 1 1 1 1 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 0 1 0 1 0 1 1 1 1 1 1 1 1 0
 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 1 1 0 0 1 1 1 0 1]


In [47]:
np.random.seed(100)
a= np.random.randn(2,3,4)
a, a.shape, a.ndim, a[1], a[0]

(array([[[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
         [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
         [-0.18949583,  0.25500144, -0.45802699,  0.43516349]],
 
        [[-0.58359505,  0.81684707,  0.67272081, -0.10441114],
         [-0.53128038,  1.02973269, -0.43813562, -1.11831825],
         [ 1.61898166,  1.54160517, -0.25187914, -0.84243574]]]),
 (2, 3, 4),
 3,
 array([[-0.58359505,  0.81684707,  0.67272081, -0.10441114],
        [-0.53128038,  1.02973269, -0.43813562, -1.11831825],
        [ 1.61898166,  1.54160517, -0.25187914, -0.84243574]]),
 array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
        [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
        [-0.18949583,  0.25500144, -0.45802699,  0.43516349]]))

### Multiplication Rule:

In [48]:
import numpy as np

In [49]:
a= np.random.rand(2,3,3)
b= np.random.rand(1,3)
print("A: ", a, a.shape, a.ndim)
print("B: ", b, b.shape, b.ndim)
print("a*b=",a*b)
print("np.matmul(a,b)=",np.matmul(a,b.T))
print("b-Shape:",b.shape,"after transpose:", b.T.shape)

A:  [[[0.03647606 0.89041156 0.98092086]
  [0.05994199 0.89054594 0.5769015 ]
  [0.74247969 0.63018394 0.58184219]]

 [[0.02043913 0.21002658 0.54468488]
  [0.76911517 0.25069523 0.28589569]
  [0.85239509 0.97500649 0.88485329]]] (2, 3, 3) 3
B:  [[0.35950784 0.59885895 0.35479561]] (1, 3) 2
a*b= [[[0.01311343 0.53323093 0.34802642]
  [0.02154962 0.53331141 0.20468212]
  [0.26692727 0.37739129 0.20643506]]

 [[0.00734803 0.12577629 0.1932518 ]
  [0.27650294 0.15013108 0.10143454]
  [0.30644272 0.58389136 0.31394207]]]
np.matmul(a,b)= [[[0.89437077]
  [0.75954314]
  [0.85075362]]

 [[0.32637613]
  [0.52806855]
  [1.20427615]]]
b-Shape: (1, 3) after transpose: (3, 1)


## [4. Create Numpy Array](#h_cell)
<a id='carray_cell'></a>

1. `np.array()`: create a numpy array.
2. `np.random.rand()`: create a random numpy array with given shape.
3. `np.ones((2,3))`: create a tensor with one.
4. `np.zeors()`: create a tensor with $0$
5. `np.arange(start, end, step)`:
6. `np.empty()`: The `np.empty()` call allocates memory for the tensor, but does not initialize it with any values - so what you're seeing is whatever was in memory at the time of allocation.
6. ``np.*_like(x)`: Often, when you're performing operations on two or more tensors, they will need to be of the same *shape* - that is, having the same number of dimensions and the same number of cells in each dimension. For that, we have the `np.*_like()` methods.
    1. `np.empty_like(x):`
    2. `np.zeros_like(x):`
    3. `np.empty_like(x):`

In [50]:
zeros = np.zeros((2, 3))
print(zeros)

ones = np.ones((2, 3))
print(ones)

np.random.seed(1729)
random = np.random.rand(2, 3)
print(random)

x = np.empty((3, 4))
print(type(x))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.2121586  0.25901824 0.42352188]
 [0.71966101 0.69225093 0.72817482]]
<class 'numpy.ndarray'>
[[1.74976547 0.3426804  1.1530358  0.25243604]
 [0.98132079 0.51421884 0.22117967 1.07004333]
 [0.18949583 0.25500144 0.45802699 0.43516349]]


In [51]:
# np.arrange():
zero_to_ten = np.arange(start=0, stop=10, step=1, dtype=float)
zero_to_ten.astype(int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
## np.*_like()
x = np.empty((2, 2, 3))
print(x.shape)
print(x)

empty_like_x = np.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = np.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = np.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

(2, 2, 3)
[[[1.74976547 0.3426804  1.1530358 ]
  [0.25243604 0.98132079 0.51421884]]

 [[0.22117967 1.07004333 0.18949583]
  [0.25500144 0.45802699 0.43516349]]]
(2, 2, 3)
[[[1.74976547 0.3426804  1.1530358 ]
  [0.25243604 0.98132079 0.51421884]]

 [[0.22117967 1.07004333 0.18949583]
  [0.25500144 0.45802699 0.43516349]]]
(2, 2, 3)
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
(2, 2, 3)
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


## [5. Data Type:](#h_cell)
<a id='dtype_cell'></a>

In [53]:
zero_to_ten = np.arange(start=0, stop=10, step=1, dtype=float) # declare a float data type
zero_to_ten.astype(int) # change the data type

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## [6. Math and Logical Operations:](#h_cell)
<a id='math_cell'></a>

In [54]:
ones = np.zeros((2, 2)) + 1 #addition ones.add()
ones=np.add(ones,100)
twos = np.ones((2, 2)) * 2 #multiplication
threes = (np.ones((2, 2)) * 7 - 1) / 2 # complex operation
fours = twos ** 2 # squre
sqrt2s = twos ** 0.5 ## squre root

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

[[101. 101.]
 [101. 101.]]
[[2. 2.]
 [2. 2.]]
[[3. 3.]
 [3. 3.]]
[[4. 4.]
 [4. 4.]]
[[1.41421356 1.41421356]
 [1.41421356 1.41421356]]


1. `np.clip(a, a_min, a_max, out=None):` It is used to limit the values of an array or a scalar within a specified range.
- a = array that should be cliped.

In [55]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
a_clipped = np.clip(a, 2, 4)
a_clipped

array([2, 2, 3, 4, 4])

### 6.1 Matrix multiplication
PyTorch implements matrix multiplication functionality in the `torch.matmul()` method.

1. The inner dimensions must match:

        (3, 2) @ (3, 2) won't work
        (2, 3) @ (3, 2) will work
        (3, 2) @ (2, 3) will work
2. The resulting matrix has the shape of the outer dimensions:

        (2, 3) @ (3, 2) -> (2, 2)
        (3, 2) @ (2, 3) -> (3, 3)

### 6.2 Element wise multiplication:
PyTorch implements multiplication functionality in the `torch.mul()` or `*` method.

        (3, 2) @ (2, 3) won't work
        (2, 3) @ (3, 3) will work

In [56]:
a = np.array([1, 2, 3])
print(a.shape, a.ndim)
element_wise_mul=a*a # Element wise multiplication: [1*1, 2*2, 3*3]=[1, 4, 9]
print("Element-Wise-Multiplication",element_wise_mul)
print("Element-Wise-Multiplication: np.multiply()",np.multiply(a, a))

print("Matrix-Multiplication:", np.matmul(a, a))
print("Matrix-Multiplication:", np.dot(a, a))

(3,) 1
Element-Wise-Multiplication [1 4 9]
Element-Wise-Multiplication: np.multiply() [1 4 9]
Matrix-Multiplication: 14
Matrix-Multiplication: 14


In [57]:
# Shapes need to be in the right way  
tensor_A = np.array([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=np.float32)

tensor_B = np.array([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=np.float32)
print(f"tensor_A: {tensor_A.shape} \t {tensor_A.ndim}")
print(f"tensor_B: {tensor_B.shape} \t {tensor_B.ndim}")

print("Element wise:",np.multiply(tensor_A, tensor_B))
print("Transpose:",tensor_A.T.shape)

np.matmul(tensor_A.T, tensor_B) 

tensor_A: (3, 2) 	 2
tensor_B: (3, 2) 	 2
Element wise: [[ 7. 20.]
 [24. 44.]
 [45. 72.]]
Transpose: (2, 3)


array([[ 76., 103.],
       [100., 136.]], dtype=float32)

#### Element wise Multiplication:
$$[m\times n\times o] * [p\times q\times r]=[m\times n\times o]\text{ this will be the new shape}$$
* Each tensor must have at least one dimension - no empty tensors.
* Comparing the dimension sizes of the two tensors, **going from last to first:**
    * Each dimension must be equal $m=p\;, n=q,\; o=r $, **or**
    * One of the dimensions must be of size 1, $p=1\;, q=1,\; o=r=1 $**or**
    * The dimension does not exist in one of the tensors $q=1,\; o=r=1 $

In [58]:
np.random.seed(100)
a= np.random.randint(1,3,(2,3,4))
b= np.random.randint(1,3,(1,4))
print(f"a*a={a*a},\n\na*b={(a*b)},\na.shape={a.shape},\t b.shape={b.shape}")

a*a=[[[1 1 4 4]
  [4 4 1 1]
  [1 1 1 4]]

 [[1 1 1 1]
  [4 1 1 4]
  [1 4 1 1]]],

a*b=[[[1 2 4 4]
  [2 4 2 2]
  [1 2 2 4]]

 [[1 2 2 2]
  [2 2 2 4]
  [1 4 2 2]]],
a.shape=(2, 3, 4),	 b.shape=(1, 4)


In [59]:
a = np.ones((4, 3, 2))

b = a * np.random.randn(   2) # 3rd & 2nd dims identical to a, dim 1 absent
print("b:", b[:1])


c = a * np.random.randn( 3, 1) # 3rd dim = 1, 2nd dim identical to a
print("C:",c)

d = a * np.random.randn(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print("d", d)


b: [[[-0.45802699  0.43516349]
  [-0.45802699  0.43516349]
  [-0.45802699  0.43516349]]]
C: [[[-0.58359505 -0.58359505]
  [ 0.81684707  0.81684707]
  [ 0.67272081  0.67272081]]

 [[-0.58359505 -0.58359505]
  [ 0.81684707  0.81684707]
  [ 0.67272081  0.67272081]]

 [[-0.58359505 -0.58359505]
  [ 0.81684707  0.81684707]
  [ 0.67272081  0.67272081]]

 [[-0.58359505 -0.58359505]
  [ 0.81684707  0.81684707]
  [ 0.67272081  0.67272081]]]
d [[[-0.10441114 -0.53128038]
  [-0.10441114 -0.53128038]
  [-0.10441114 -0.53128038]]

 [[-0.10441114 -0.53128038]
  [-0.10441114 -0.53128038]
  [-0.10441114 -0.53128038]]

 [[-0.10441114 -0.53128038]
  [-0.10441114 -0.53128038]
  [-0.10441114 -0.53128038]]

 [[-0.10441114 -0.53128038]
  [-0.10441114 -0.53128038]
  [-0.10441114 -0.53128038]]]


In [60]:
a = np.ones((4, 3, 2))

b = a * np.random.randn(4, 3)    # dimensions must match last-to-first

c = a * np.rand(   2, 3) # both 3rd & 2nd dims different

d = a * np.rand((0, ))   # can't broadcast with an empty tensor

ValueError: operands could not be broadcast together with shapes (4,3,2) (4,3) 

## [7. Manipulating Tensor Shapes](#h_cell)
<a id='mts_cell'></a>

## [8. Array Accessing](#h_cell)
<a id='aa_cell'></a>

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[:, 1:4])


[[2 3 4]
 [7 8 9]]


In [ ]:

xy= np.loadtxt("../data/wine/wine.csv", delimiter=',', dtype=np.float32, skiprows=1)
n_samples=xy.shape[0]
# xy
xy[:, 1:]


array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]], dtype=float32)

## [9. Important Methods:](#h_cell)
<a id='im_cell'></a>

1. `numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)`:  is used to create an array of evenly spaced values over a specified range.

In [ ]:
arr = np.linspace(0, 1, num=10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
